spring:
  application:
    name: academic-guidance-service
  config:
    import: optional:config-service:https://root:4c4d3mIc5ec12eT@guidance-config-service.herokuapp.com
  cloud:
    config:
      uri: https://guidance-config-service.herokuapp.com
      discovery:
        enabled: true
        service-id: config-service
      fail-fast: true
      name: academic-guidance-service
      profile: development
      username: root
      password: 4c4d3mIc5ec12eT
      label: main